repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

ci:
  autofix_prs: true
  autofix_commit_msg: "chore: pre-commit auto fixes"
