/**
 * Docs sidebar.
 *
 * AUTOGENERATED from the `docs/` directory tree rather than a hand-maintained
 * id list. The previous hand-written list referenced 22 doc ids that were never
 * authored (`getting-started/*`, `concepts/*`, `api/*`, `migration/*`,
 * `advanced/*`, `dsl/syntax`, ...), so every `docusaurus build` failed with
 * "Invalid sidebar file" — which is what kept both `Deploy Docs to GitHub Pages`
 * and `qontinui CI` red on main.
 *
 * An autogenerated sidebar cannot drift from the filesystem, so adding or
 * removing a doc can never red main this way again. Control ordering and labels
 * from the docs themselves:
 *   - `sidebar_position` / `sidebar_label` frontmatter on each page
 *   - `_category_.json` in a subdirectory for that category's label + position
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
